version: '3'

services: 
  app:
    build:
      context: ./node
      dockerfile: dockerfile.prod
    image: 1aquila1/node-app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
       - db

  db:
    build:
      context: ./
      dockerfile: dockerfile.mysql.prod
    image: 1aquila1/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - node-network

  nginx:
    build:
      context: ./
      dockerfile: dockerfile.nginx.prod
    image: 1aquila1/nginx-app
    container_name: nginx
    ports:
      - "8080:80"
    depends_on: 
       - app
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge      
